{% set version = "1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-missforest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/missForest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/missForest/missForest_{{ version }}.tar.gz
  sha256: 417055a03b02ad8359cf1bdc8f89d49531a3a8ee2c98edf90c8a01432f44838d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-foreach
    - r-itertools
    - r-randomforest
  run:
    - r-base
    - r-foreach
    - r-itertools
    - r-randomforest

test:
  commands:
    - $R -e "library('missForest')"           # [not win]
    - "\"%R%\" -e \"library('missForest')\""  # [win]

about:
  home: http://www.r-project.org, https://github.com/stekhoven/missForest
  license: GPL-2.0-or-later
  summary: The function 'missForest' in this package is used to impute missing values particularly in the case of mixed-type data. It uses a random forest trained on the observed values of a data matrix to predict the missing values. It can be used to impute continuous and/or categorical data including complex interactions
    and non-linear relations. It yields an out-of-bag (OOB) imputation error estimate without the need of a test set or elaborate cross-validation. It can be run in parallel to  save computation time.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
