appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aNp8yhXk9PX2nfRApd9s0+FdluF2CEBf8ThsTYw1pnkzVQlXTn5Mt6V3I1W0Qc6scrF8Ru7mQiPIxh6Idw3yyeAl32abNYNqjKmTceDM0BnyRAro+tnXinCqk3Q/dF/VQimcMBJZt7ZZguuyfEL8vtkBq2H9pn6H/FyeO4uY1U1bsgA0kkCzMoLUK0GixzVveIMFaG4TrAGyc7O4gcLZBcqZMaxMiffcY39+XYzwpAIe4VcjBgNtVN6qrD6Zuh3eX2n5NqtzVWP8kc5rsbSz+noea3CDD4WW41sVnptNqlv+saDwHfgNYXz8bT/e88cul8QWjxaQgfldGthuDVI/FRPrcDoBDA9rB+LH4bWSGyx3CvGeNBLHqMoFWpugoGZ/gGiHPF+Rij7LU6VRrj5Tlddtj4gSogKkj1domNCbrxs8f56p/DwPZDzQeAq32te68Kb4BzvyYumVrl5tKp0UYQ6NSVC2To1xakrrQtctrAs6dEe0/BWfRww3AEYbJX+7lcYvaBY87ER3N9Vc4cGbwb5F7kZXJcK++2ZL6Aku6y2XDjYqwm6Rx3Vje2Ti8Gf/A9JiCHSqsgUnpVjUBJK7yo38i30At7E9jX+2quI7jWqNn9sG+xUPU31J1xSaL53ZqhiPUtH9XvtI5ZM/aKwuTdiw/g5jOMhRk4NfY/30KCo=}
bot:
  automerge: true
