travis:
  secure:
    BINSTAR_TOKEN: Z4FJlKqiuj437ihVYOOoalt9FhNvCNtI8sITAn6vfvA8UCbgohsjFPVC6ERjryLQQRFCzRPieGmGlYe9D6fL448e4yR7zyry4+Ij5igLZsahmGZ9RBnGCH4jmwvP13NsQPFMHz0WFVARuSQwyNQBleRNx9BRBBRleyWg1AxXr0NROLIk0tSp5lkDcXiVCFbGG3XsSu1rbmhNV4pALAkd8Tr01b6TKRTRyqrox8EyYUB3BR16V7BVK8THO5lu1mlwzk8WJku5seoorhQPIF0qTJ+jn2cdtZ+ri0Hs7mxCNjlj9PwffD++duYuRqX7j2QGcN49W/kkMe2ciNNsu5ddMRrs/tB6pRdCfkVW0aSfg0KbGKC6ZILGvM3TMqLwGZ4sorVybiAK4QfnulOG+O4YyWY+QLo824B7WC2LXihdmMhirAMsOlLwhP8/3vppCvTBw65AdwCJxYDrNUgaJnLLfn2TVR0A8Nox+RxSTzRLmMmGsJ5b7tCS03TlESyrbCkXF7TT9O2ui1l/eY5dIY33FGg8cfaQ0hJgQ0dpSJnBWmuDvd2NaB5m7fH53mF/E3iXZf5aPyG6ns6tIeGvwHm2ee/JDQUSBW1Nr5Gux5JWDn+PiiyKOa6iWUeL3qH8BoamjeqmySjpucrP8yJXwqkl2qlCrKFO4tuDGRYvB7umLdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
